### ISSUE TITLE
document use of arrays in README

### ISSUE THREAD

**Issue by elf-pavlik** [nicola/simplerdf#32]
currently README shows how to define _foaf:knows_ as an array, but it doesn't say anything about using it. can one for example do

```
me.knows = [ "https://alice.example/#id", "https://bob.example/#id"]
```

or one always needs to use _.push()_ on properties defined as an array?

if one can at any point simply assign (=) to any property a single value or array of values, i don't understand point in needing to define `'@array': true` since each property could always get initialized with an empty array and one could than either _.push()_ or assign (=) single value or array.

**Comment by bergos** [comment]
It should be possible to write values to a property using an Array. Reading is not possible, because of the setter and getter methods. Once we have Proxy support in all JS engines and a SimpleRDF Proxy implementation, reading should also work.

With `@array` you can rely on the result type. That's different to JSONLD. JSON-LD dynamically creates arrays, depending on the number of values. That causes ugly `if (Array.isArray())` code.

**Comment by nicola** [comment]
@elf-pavlik thanks for your issue,
I am going to add this in the doc ;)

**Comment by nicola** [comment]
I consider this as fixed in the latest README
